<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CarBrandSeeder extends Seeder
{
    public function run(): void
    {

        DB::table('car_brands')->insert([
            ['name' => 'Abarth'],
            ['name' => 'Acura'],
            ['name' => 'Alfa Romeo'],
            ['name' => 'Alpine'],
            ['name' => 'Alpina'],
            ['name' => 'Aston Martin'],
            ['name' => 'Audi'],
            ['name' => 'Bentley'],
            ['name' => 'Buick'],
            ['name' => 'BYD'],
            ['name' => 'Cadillac'],
            ['name' => 'Chevrolet'],
            ['name' => 'Chrysler'],
            ['name' => 'Citroen'],
            ['name' => 'Cupra'],
            ['name' => 'Dacia'],
            ['name' => 'Daewoo'],
            ['name' => 'Dodge'],
            ['name' => 'Ferrari'],
            ['name' => 'Fiat'],
            ['name' => 'Ford'],
            ['name' => 'Genesis'],
            ['name' => 'Honda'],
            ['name' => 'Hyundai'],
            ['name' => 'Infiniti'],
            ['name' => 'Isuzu'],
            ['name' => 'Jaguar'],
            ['name' => 'Jeep'],
            ['name' => 'Kia'],
            ['name' => 'Koenigsegg'],
            ['name' => 'Lada'],
            ['name' => 'Lamborghini'],
            ['name' => 'Lancia'],
            ['name' => 'Land Rover'],
            ['name' => 'Lexus'],
            ['name' => 'Lincoln'],
            ['name' => 'Lotus'],
            ['name' => 'Maserati'],
            ['name' => 'Mazda'],
            ['name' => 'McLaren'],
            ['name' => 'Mercedes-AMG'],
            ['name' => 'Mercedes-Benz'],
            ['name' => 'Mercury'],
            ['name' => 'MG'],
            ['name' => 'Mini'],
            ['name' => 'Mitsubishi'],
            ['name' => 'Morgan'],
            ['name' => 'Morris'],
            ['name' => 'Nissan'],
            ['name' => 'Oldsmobile'],
            ['name' => 'Opel'],
            ['name' => 'Peugeot'],
            ['name' => 'Plymouth'],
            ['name' => 'Polestar'],
            ['name' => 'Polski Fiat'],
            ['name' => 'Pontiac'],
            ['name' => 'Porsche'],
            ['name' => 'Proton'],
            ['name' => 'Renault'],
            ['name' => 'Rolls-Royce'],
            ['name' => 'Saab'],
            ['name' => 'SEAT'],
            ['name' => 'Smart'],
            ['name' => 'SsangYong'],
            ['name' => 'Subaru'],
            ['name' => 'Suzuki'],
            ['name' => 'Skoda'],
            ['name' => 'Tesla'],
            ['name' => 'Toyota'],
            ['name' => 'Trabant'],
            ['name' => 'UAZ'],
            ['name' => 'Vauxhall'],
            ['name' => 'Volga'],
            ['name' => 'Volkswagen'],
            ['name' => 'Volvo'],
            ['name' => 'Wartburg'],
            ['name' => 'XPeng'],
            ['name' => 'Zastava']
        ]);
    }
}
