<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CarModelSeeder extends Seeder
{
    public function run(): void
    {

        DB::table('car_models')->insert([
            ['id' => 1, 'name' => '124 Spider', 'brand_id' => 1],
            ['id' => 2, 'name' => '500', 'brand_id' => 1],
            ['id' => 3, 'name' => '500C', 'brand_id' => 1],
            ['id' => 4, 'name' => '595', 'brand_id' => 1],
            ['id' => 5, 'name' => '695', 'brand_id' => 1],
            ['id' => 6, 'name' => 'Grande Punto', 'brand_id' => 1],
            ['id' => 7, 'name' => 'Punto Evo', 'brand_id' => 1],
            ['id' => 8, 'name' => 'CL', 'brand_id' => 2],
            ['id' => 9, 'name' => 'ILX', 'brand_id' => 2],
            ['id' => 10, 'name' => 'Integra', 'brand_id' => 2],
            ['id' => 11, 'name' => 'Legend', 'brand_id' => 2],
            ['id' => 12, 'name' => 'MDX', 'brand_id' => 2],
            ['id' => 13, 'name' => 'NSX', 'brand_id' => 2],
            ['id' => 14, 'name' => 'RDX', 'brand_id' => 2],
            ['id' => 15, 'name' => 'RSX', 'brand_id' => 2],
            ['id' => 16, 'name' => 'TL', 'brand_id' => 2],
            ['id' => 17, 'name' => 'TSX', 'brand_id' => 2],
            ['id' => 18, 'name' => '145', 'brand_id' => 3],
            ['id' => 19, 'name' => '147', 'brand_id' => 3],
            ['id' => 20, 'name' => '156', 'brand_id' => 3],
            ['id' => 21, 'name' => '159', 'brand_id' => 3],
            ['id' => 22, 'name' => 'Brera', 'brand_id' => 3],
            ['id' => 23, 'name' => 'Giulia', 'brand_id' => 3],
            ['id' => 24, 'name' => 'Giulietta', 'brand_id' => 3],
            ['id' => 25, 'name' => 'GT', 'brand_id' => 3],
            ['id' => 26, 'name' => 'GTV', 'brand_id' => 3],
            ['id' => 27, 'name' => 'MiTo', 'brand_id' => 3],
            ['id' => 28, 'name' => 'Spider', 'brand_id' => 3],
            ['id' => 29, 'name' => 'Stelvio', 'brand_id' => 3],
            ['id' => 30, 'name' => 'Tonale', 'brand_id' => 3],
            ['id' => 31, 'name' => 'A110', 'brand_id' => 4],
            ['id' => 32, 'name' => 'A310', 'brand_id' => 4],
            ['id' => 33, 'name' => 'GTA', 'brand_id' => 4],
            ['id' => 34, 'name' => 'B3', 'brand_id' => 5],
            ['id' => 35, 'name' => 'B4', 'brand_id' => 5],
            ['id' => 36, 'name' => 'B5', 'brand_id' => 5],
            ['id' => 37, 'name' => 'B6', 'brand_id' => 5],
            ['id' => 38, 'name' => 'B7', 'brand_id' => 5],
            ['id' => 39, 'name' => 'D3', 'brand_id' => 5],
            ['id' => 40, 'name' => 'D5', 'brand_id' => 5],
            ['id' => 41, 'name' => 'XD3', 'brand_id' => 5],
            ['id' => 42, 'name' => 'Cygnet', 'brand_id' => 6],
            ['id' => 43, 'name' => 'DB7', 'brand_id' => 6],
            ['id' => 44, 'name' => 'DB9', 'brand_id' => 6],
            ['id' => 45, 'name' => 'DBS', 'brand_id' => 6],
            ['id' => 46, 'name' => 'DBX', 'brand_id' => 6],
            ['id' => 47, 'name' => 'Rapide', 'brand_id' => 6],
            ['id' => 48, 'name' => 'V12 Vantage', 'brand_id' => 6],
            ['id' => 49, 'name' => 'V8 Vantage', 'brand_id' => 6],
            ['id' => 50, 'name' => 'Vanquish', 'brand_id' => 6],
            ['id' => 51, 'name' => 'Virage', 'brand_id' => 6],
            ['id' => 52, 'name' => 'A1', 'brand_id' => 7],
            ['id' => 53, 'name' => 'A2', 'brand_id' => 7],
            ['id' => 54, 'name' => 'A3', 'brand_id' => 7],
            ['id' => 55, 'name' => 'A4', 'brand_id' => 7],
            ['id' => 56, 'name' => 'A5', 'brand_id' => 7],
            ['id' => 57, 'name' => 'A6', 'brand_id' => 7],
            ['id' => 58, 'name' => 'A7', 'brand_id' => 7],
            ['id' => 59, 'name' => 'A8', 'brand_id' => 7],
            ['id' => 60, 'name' => 'Q2', 'brand_id' => 7],
            ['id' => 61, 'name' => 'Q3', 'brand_id' => 7],
            ['id' => 62, 'name' => 'Q5', 'brand_id' => 7],
            ['id' => 63, 'name' => 'Q7', 'brand_id' => 7],
            ['id' => 64, 'name' => 'Q8', 'brand_id' => 7],
            ['id' => 65, 'name' => 'R8', 'brand_id' => 7],
            ['id' => 66, 'name' => 'TT', 'brand_id' => 7],
            ['id' => 67, 'name' => 'Bentayga', 'brand_id' => 8],
            ['id' => 68, 'name' => 'Continental Flying Spur', 'brand_id' => 8],
            ['id' => 69, 'name' => 'Continental GT', 'brand_id' => 8],
            ['id' => 70, 'name' => 'Continental GTC', 'brand_id' => 8],
            ['id' => 71, 'name' => 'Flying Spur', 'brand_id' => 8],
            ['id' => 72, 'name' => 'Mulsanne', 'brand_id' => 8],
            ['id' => 73, 'name' => 'LeSabre', 'brand_id' => 9],
            ['id' => 74, 'name' => 'Park Avenue', 'brand_id' => 9],
            ['id' => 75, 'name' => 'Regal', 'brand_id' => 9],
            ['id' => 76, 'name' => 'Riviera', 'brand_id' => 9],
            ['id' => 77, 'name' => 'Atto 3', 'brand_id' => 10],
            ['id' => 78, 'name' => 'Dolphin', 'brand_id' => 10],
            ['id' => 79, 'name' => 'Han', 'brand_id' => 10],
            ['id' => 80, 'name' => 'Seal', 'brand_id' => 10],
            ['id' => 81, 'name' => 'Tang', 'brand_id' => 10],
            ['id' => 82, 'name' => 'ATS', 'brand_id' => 11],
            ['id' => 83, 'name' => 'BLS', 'brand_id' => 11],
            ['id' => 84, 'name' => 'CTS', 'brand_id' => 11],
            ['id' => 85, 'name' => 'DeVille', 'brand_id' => 11],
            ['id' => 86, 'name' => 'Escalade', 'brand_id' => 11],
            ['id' => 87, 'name' => 'SRX', 'brand_id' => 11],
            ['id' => 88, 'name' => 'STS', 'brand_id' => 11],
            ['id' => 89, 'name' => 'XLR', 'brand_id' => 11],
            ['id' => 90, 'name' => 'Aveo', 'brand_id' => 12],
            ['id' => 91, 'name' => 'Camaro', 'brand_id' => 12],
            ['id' => 92, 'name' => 'Captiva', 'brand_id' => 12],
            ['id' => 93, 'name' => 'Corvette', 'brand_id' => 12],
            ['id' => 94, 'name' => 'Cruze', 'brand_id' => 12],
            ['id' => 95, 'name' => 'Epica', 'brand_id' => 12],
            ['id' => 96, 'name' => 'HHR', 'brand_id' => 12],
            ['id' => 97, 'name' => 'Kalos', 'brand_id' => 12],
            ['id' => 98, 'name' => 'Lacetti', 'brand_id' => 12],
            ['id' => 99, 'name' => 'Malibu', 'brand_id' => 12],
            ['id' => 100, 'name' => 'Matiz', 'brand_id' => 12],
            ['id' => 101, 'name' => 'Orlando', 'brand_id' => 12],
            ['id' => 102, 'name' => 'Spark', 'brand_id' => 12],
            ['id' => 103, 'name' => 'Suburban', 'brand_id' => 12],
            ['id' => 104, 'name' => 'Tahoe', 'brand_id' => 12],
            ['id' => 105, 'name' => 'Trax', 'brand_id' => 12],
            ['id' => 106, 'name' => '300C', 'brand_id' => 13],
            ['id' => 107, 'name' => 'Crossfire', 'brand_id' => 13],
            ['id' => 108, 'name' => 'Grand Voyager', 'brand_id' => 13],
            ['id' => 109, 'name' => 'PT Cruiser', 'brand_id' => 13],
            ['id' => 110, 'name' => 'Sebring', 'brand_id' => 13],
            ['id' => 111, 'name' => 'Voyager', 'brand_id' => 13],
            ['id' => 112, 'name' => 'Berlingo', 'brand_id' => 14],
            ['id' => 113, 'name' => 'C1', 'brand_id' => 14],
            ['id' => 114, 'name' => 'C2', 'brand_id' => 14],
            ['id' => 115, 'name' => 'C3', 'brand_id' => 14],
            ['id' => 116, 'name' => 'C3 Aircross', 'brand_id' => 14],
            ['id' => 117, 'name' => 'C4', 'brand_id' => 14],
            ['id' => 118, 'name' => 'C4 Cactus', 'brand_id' => 14],
            ['id' => 119, 'name' => 'C4 Picasso', 'brand_id' => 14],
            ['id' => 120, 'name' => 'C5', 'brand_id' => 14],
            ['id' => 121, 'name' => 'C5 Aircross', 'brand_id' => 14],
            ['id' => 122, 'name' => 'C6', 'brand_id' => 14],
            ['id' => 123, 'name' => 'DS3', 'brand_id' => 14],
            ['id' => 124, 'name' => 'DS4', 'brand_id' => 14],
            ['id' => 125, 'name' => 'DS5', 'brand_id' => 14],
            ['id' => 126, 'name' => 'Jumper', 'brand_id' => 14],
            ['id' => 127, 'name' => 'Jumpy', 'brand_id' => 14],
            ['id' => 128, 'name' => 'Saxo', 'brand_id' => 14],
            ['id' => 129, 'name' => 'Xsara', 'brand_id' => 14],
            ['id' => 130, 'name' => 'Xsara Picasso', 'brand_id' => 14],
            ['id' => 131, 'name' => 'Ateca', 'brand_id' => 15],
            ['id' => 132, 'name' => 'Born', 'brand_id' => 15],
            ['id' => 133, 'name' => 'Formentor', 'brand_id' => 15],
            ['id' => 134, 'name' => 'Leon', 'brand_id' => 15],
            ['id' => 135, 'name' => 'Leon Sportstourer', 'brand_id' => 15],
            ['id' => 136, 'name' => 'Dokker', 'brand_id' => 16],
            ['id' => 137, 'name' => 'Duster', 'brand_id' => 16],
            ['id' => 138, 'name' => 'Jogger', 'brand_id' => 16],
            ['id' => 139, 'name' => 'Lodgy', 'brand_id' => 16],
            ['id' => 140, 'name' => 'Logan', 'brand_id' => 16],
            ['id' => 141, 'name' => 'Sandero', 'brand_id' => 16],
            ['id' => 142, 'name' => 'Spring', 'brand_id' => 16],
            ['id' => 143, 'name' => 'Espero', 'brand_id' => 17],
            ['id' => 144, 'name' => 'Kalos', 'brand_id' => 17],
            ['id' => 145, 'name' => 'Lanos', 'brand_id' => 17],
            ['id' => 146, 'name' => 'Leganza', 'brand_id' => 17],
            ['id' => 147, 'name' => 'Matiz', 'brand_id' => 17],
            ['id' => 148, 'name' => 'Nubira', 'brand_id' => 17],
            ['id' => 149, 'name' => 'Tacuma', 'brand_id' => 17],
            ['id' => 150, 'name' => 'Avenger', 'brand_id' => 18],
            ['id' => 151, 'name' => 'Caliber', 'brand_id' => 18],
            ['id' => 152, 'name' => 'Challenger', 'brand_id' => 18],
            ['id' => 153, 'name' => 'Charger', 'brand_id' => 18],
            ['id' => 154, 'name' => 'Durango', 'brand_id' => 18],
            ['id' => 155, 'name' => 'Journey', 'brand_id' => 18],
            ['id' => 156, 'name' => 'Nitro', 'brand_id' => 18],
            ['id' => 157, 'name' => 'Ram', 'brand_id' => 18],
            ['id' => 158, 'name' => 'Viper', 'brand_id' => 18],
            ['id' => 159, 'name' => '360', 'brand_id' => 19],
            ['id' => 160, 'name' => '458', 'brand_id' => 19],
            ['id' => 161, 'name' => '488', 'brand_id' => 19],
            ['id' => 162, 'name' => '599', 'brand_id' => 19],
            ['id' => 163, 'name' => '612', 'brand_id' => 19],
            ['id' => 164, 'name' => 'California', 'brand_id' => 19],
            ['id' => 165, 'name' => 'F12', 'brand_id' => 19],
            ['id' => 166, 'name' => 'F355', 'brand_id' => 19],
            ['id' => 167, 'name' => 'F430', 'brand_id' => 19],
            ['id' => 168, 'name' => 'FF', 'brand_id' => 19],
            ['id' => 169, 'name' => 'GTC4Lusso', 'brand_id' => 19],
            ['id' => 170, 'name' => 'Portofino', 'brand_id' => 19],
            ['id' => 171, 'name' => '124 Spider', 'brand_id' => 20],
            ['id' => 172, 'name' => '500', 'brand_id' => 20],
            ['id' => 173, 'name' => '500L', 'brand_id' => 20],
            ['id' => 174, 'name' => '500X', 'brand_id' => 20],
            ['id' => 175, 'name' => 'Barchetta', 'brand_id' => 20],
            ['id' => 176, 'name' => 'Bravo', 'brand_id' => 20],
            ['id' => 177, 'name' => 'Croma', 'brand_id' => 20],
            ['id' => 178, 'name' => 'Doblo', 'brand_id' => 20],
            ['id' => 179, 'name' => 'Ducato', 'brand_id' => 20],
            ['id' => 180, 'name' => 'Freemont', 'brand_id' => 20],
            ['id' => 181, 'name' => 'Grande Punto', 'brand_id' => 20],
            ['id' => 182, 'name' => 'Panda', 'brand_id' => 20],
            ['id' => 183, 'name' => 'Punto', 'brand_id' => 20],
            ['id' => 184, 'name' => 'Qubo', 'brand_id' => 20],
            ['id' => 185, 'name' => 'Scudo', 'brand_id' => 20],
            ['id' => 186, 'name' => 'Stilo', 'brand_id' => 20],
            ['id' => 187, 'name' => 'Tipo', 'brand_id' => 20],
            ['id' => 188, 'name' => 'Ulysse', 'brand_id' => 20],
            ['id' => 189, 'name' => 'B-Max', 'brand_id' => 21],
            ['id' => 190, 'name' => 'C-Max', 'brand_id' => 21],
            ['id' => 191, 'name' => 'EcoSport', 'brand_id' => 21],
            ['id' => 192, 'name' => 'Edge', 'brand_id' => 21],
            ['id' => 193, 'name' => 'Escape', 'brand_id' => 21],
            ['id' => 194, 'name' => 'Escort', 'brand_id' => 21],
            ['id' => 195, 'name' => 'Explorer', 'brand_id' => 21],
            ['id' => 196, 'name' => 'Fiesta', 'brand_id' => 21],
            ['id' => 197, 'name' => 'Focus', 'brand_id' => 21],
            ['id' => 198, 'name' => 'Fusion', 'brand_id' => 21],
            ['id' => 199, 'name' => 'Galaxy', 'brand_id' => 21],
            ['id' => 200, 'name' => 'Ka', 'brand_id' => 21],
            ['id' => 201, 'name' => 'Kuga', 'brand_id' => 21],
            ['id' => 202, 'name' => 'Mondeo', 'brand_id' => 21],
            ['id' => 203, 'name' => 'Mustang', 'brand_id' => 21],
            ['id' => 204, 'name' => 'Puma', 'brand_id' => 21],
            ['id' => 205, 'name' => 'Ranger', 'brand_id' => 21],
            ['id' => 206, 'name' => 'S-Max', 'brand_id' => 21],
            ['id' => 207, 'name' => 'Tourneo Connect', 'brand_id' => 21],
            ['id' => 208, 'name' => 'Tourneo Courier', 'brand_id' => 21],
            ['id' => 209, 'name' => 'Transit', 'brand_id' => 21],
            ['id' => 210, 'name' => 'Transit Connect', 'brand_id' => 21],
            ['id' => 211, 'name' => 'G70', 'brand_id' => 22],
            ['id' => 212, 'name' => 'G80', 'brand_id' => 22],
            ['id' => 213, 'name' => 'G90', 'brand_id' => 22],
            ['id' => 214, 'name' => 'GV60', 'brand_id' => 22],
            ['id' => 215, 'name' => 'GV70', 'brand_id' => 22],
            ['id' => 216, 'name' => 'GV80', 'brand_id' => 22],
            ['id' => 217, 'name' => 'Accord', 'brand_id' => 23],
            ['id' => 218, 'name' => 'Civic', 'brand_id' => 23],
            ['id' => 219, 'name' => 'CR-V', 'brand_id' => 23],
            ['id' => 220, 'name' => 'CR-Z', 'brand_id' => 23],
            ['id' => 221, 'name' => 'E', 'brand_id' => 23],
            ['id' => 222, 'name' => 'FR-V', 'brand_id' => 23],
            ['id' => 223, 'name' => 'HR-V', 'brand_id' => 23],
            ['id' => 224, 'name' => 'Insight', 'brand_id' => 23],
            ['id' => 225, 'name' => 'Jazz', 'brand_id' => 23],
            ['id' => 226, 'name' => 'Legend', 'brand_id' => 23],
            ['id' => 227, 'name' => 'NSX', 'brand_id' => 23],
            ['id' => 228, 'name' => 'Prelude', 'brand_id' => 23],
            ['id' => 229, 'name' => 'S2000', 'brand_id' => 23],
            ['id' => 230, 'name' => 'Accent', 'brand_id' => 24],
            ['id' => 231, 'name' => 'Bayon', 'brand_id' => 24],
            ['id' => 232, 'name' => 'Coupe', 'brand_id' => 24],
            ['id' => 233, 'name' => 'Elantra', 'brand_id' => 24],
            ['id' => 234, 'name' => 'Genesis Coupe', 'brand_id' => 24],
            ['id' => 235, 'name' => 'Getz', 'brand_id' => 24],
            ['id' => 236, 'name' => 'i10', 'brand_id' => 24],
            ['id' => 237, 'name' => 'i20', 'brand_id' => 24],
            ['id' => 238, 'name' => 'i30', 'brand_id' => 24],
            ['id' => 239, 'name' => 'i40', 'brand_id' => 24],
            ['id' => 240, 'name' => 'Ioniq', 'brand_id' => 24],
            ['id' => 241, 'name' => 'Ioniq 5', 'brand_id' => 24],
            ['id' => 242, 'name' => 'Ioniq 6', 'brand_id' => 24],
            ['id' => 243, 'name' => 'ix20', 'brand_id' => 24],
            ['id' => 244, 'name' => 'ix35', 'brand_id' => 24],
            ['id' => 245, 'name' => 'Kona', 'brand_id' => 24],
            ['id' => 246, 'name' => 'Matrix', 'brand_id' => 24],
            ['id' => 247, 'name' => 'Santa Fe', 'brand_id' => 24],
            ['id' => 248, 'name' => 'Sonata', 'brand_id' => 24],
            ['id' => 249, 'name' => 'Terracan', 'brand_id' => 24],
            ['id' => 250, 'name' => 'Tucson', 'brand_id' => 24],
            ['id' => 251, 'name' => 'Veloster', 'brand_id' => 24],
            ['id' => 252, 'name' => 'EX', 'brand_id' => 25],
            ['id' => 253, 'name' => 'FX', 'brand_id' => 25],
            ['id' => 254, 'name' => 'G', 'brand_id' => 25],
            ['id' => 255, 'name' => 'M', 'brand_id' => 25],
            ['id' => 256, 'name' => 'Q30', 'brand_id' => 25],
            ['id' => 257, 'name' => 'Q50', 'brand_id' => 25],
            ['id' => 258, 'name' => 'Q60', 'brand_id' => 25],
            ['id' => 259, 'name' => 'Q70', 'brand_id' => 25],
            ['id' => 260, 'name' => 'QX30', 'brand_id' => 25],
            ['id' => 261, 'name' => 'QX50', 'brand_id' => 25],
            ['id' => 262, 'name' => 'QX70', 'brand_id' => 25],
            ['id' => 263, 'name' => 'D-Max', 'brand_id' => 26],
            ['id' => 264, 'name' => 'Trooper', 'brand_id' => 26],
            ['id' => 265, 'name' => 'E-Pace', 'brand_id' => 27],
            ['id' => 266, 'name' => 'F-Pace', 'brand_id' => 27],
            ['id' => 267, 'name' => 'F-Type', 'brand_id' => 27],
            ['id' => 268, 'name' => 'I-Pace', 'brand_id' => 27],
            ['id' => 269, 'name' => 'S-Type', 'brand_id' => 27],
            ['id' => 270, 'name' => 'X-Type', 'brand_id' => 27],
            ['id' => 271, 'name' => 'XE', 'brand_id' => 27],
            ['id' => 272, 'name' => 'XF', 'brand_id' => 27],
            ['id' => 273, 'name' => 'XJ', 'brand_id' => 27],
            ['id' => 274, 'name' => 'XK', 'brand_id' => 27],
            ['id' => 275, 'name' => 'Cherokee', 'brand_id' => 28],
            ['id' => 276, 'name' => 'Commander', 'brand_id' => 28],
            ['id' => 277, 'name' => 'Compass', 'brand_id' => 28],
            ['id' => 278, 'name' => 'Grand Cherokee', 'brand_id' => 28],
            ['id' => 279, 'name' => 'Patriot', 'brand_id' => 28],
            ['id' => 280, 'name' => 'Renegade', 'brand_id' => 28],
            ['id' => 281, 'name' => 'Wrangler', 'brand_id' => 28],
            ['id' => 282, 'name' => 'Carens', 'brand_id' => 29],
            ['id' => 283, 'name' => 'Carnival', 'brand_id' => 29],
            ['id' => 284, 'name' => 'Ceed', 'brand_id' => 29],
            ['id' => 285, 'name' => 'Cerato', 'brand_id' => 29],
            ['id' => 286, 'name' => 'EV6', 'brand_id' => 29],
            ['id' => 287, 'name' => 'EV9', 'brand_id' => 29],
            ['id' => 288, 'name' => 'Magentis', 'brand_id' => 29],
            ['id' => 289, 'name' => 'Niro', 'brand_id' => 29],
            ['id' => 290, 'name' => 'Optima', 'brand_id' => 29],
            ['id' => 291, 'name' => 'Picanto', 'brand_id' => 29],
            ['id' => 292, 'name' => 'ProCeed', 'brand_id' => 29],
            ['id' => 293, 'name' => 'Rio', 'brand_id' => 29],
            ['id' => 294, 'name' => 'Sorento', 'brand_id' => 29],
            ['id' => 295, 'name' => 'Soul', 'brand_id' => 29],
            ['id' => 296, 'name' => 'Sportage', 'brand_id' => 29],
            ['id' => 297, 'name' => 'Stinger', 'brand_id' => 29],
            ['id' => 298, 'name' => 'Venga', 'brand_id' => 29],
            ['id' => 299, 'name' => 'Agera', 'brand_id' => 30],
            ['id' => 300, 'name' => 'CCX', 'brand_id' => 30],
            ['id' => 301, 'name' => 'Jesko', 'brand_id' => 30],
            ['id' => 302, 'name' => 'Regera', 'brand_id' => 30],
            ['id' => 303, 'name' => 'Kalina', 'brand_id' => 31],
            ['id' => 304, 'name' => 'Niva', 'brand_id' => 31],
            ['id' => 305, 'name' => 'Priora', 'brand_id' => 31],
            ['id' => 306, 'name' => 'Samara', 'brand_id' => 31],
            ['id' => 307, 'name' => 'Vesta', 'brand_id' => 31],
            ['id' => 308, 'name' => 'Aventador', 'brand_id' => 32],
            ['id' => 309, 'name' => 'Gallardo', 'brand_id' => 32],
            ['id' => 310, 'name' => 'Huracan', 'brand_id' => 32],
            ['id' => 311, 'name' => 'Murcielago', 'brand_id' => 32],
            ['id' => 312, 'name' => 'Urus', 'brand_id' => 32],
            ['id' => 313, 'name' => 'Delta', 'brand_id' => 33],
            ['id' => 314, 'name' => 'Kappa', 'brand_id' => 33],
            ['id' => 315, 'name' => 'Lybra', 'brand_id' => 33],
            ['id' => 316, 'name' => 'Musa', 'brand_id' => 33],
            ['id' => 317, 'name' => 'Phedra', 'brand_id' => 33],
            ['id' => 318, 'name' => 'Thema', 'brand_id' => 33],
            ['id' => 319, 'name' => 'Thesis', 'brand_id' => 33],
            ['id' => 320, 'name' => 'Voyager', 'brand_id' => 33],
            ['id' => 321, 'name' => 'Ypsilon', 'brand_id' => 33],
            ['id' => 322, 'name' => 'Zeta', 'brand_id' => 33],
            ['id' => 323, 'name' => 'Defender', 'brand_id' => 34],
            ['id' => 324, 'name' => 'Discovery', 'brand_id' => 34],
            ['id' => 325, 'name' => 'Discovery Sport', 'brand_id' => 34],
            ['id' => 326, 'name' => 'Freelander', 'brand_id' => 34],
            ['id' => 327, 'name' => 'Range Rover', 'brand_id' => 34],
            ['id' => 328, 'name' => 'Range Rover Evoque', 'brand_id' => 34],
            ['id' => 329, 'name' => 'Range Rover Sport', 'brand_id' => 34],
            ['id' => 330, 'name' => 'Range Rover Velar', 'brand_id' => 34],
            ['id' => 331, 'name' => 'CT', 'brand_id' => 35],
            ['id' => 332, 'name' => 'ES', 'brand_id' => 35],
            ['id' => 333, 'name' => 'GS', 'brand_id' => 35],
            ['id' => 334, 'name' => 'IS', 'brand_id' => 35],
            ['id' => 335, 'name' => 'LC', 'brand_id' => 35],
            ['id' => 336, 'name' => 'LFA', 'brand_id' => 35],
            ['id' => 337, 'name' => 'LS', 'brand_id' => 35],
            ['id' => 338, 'name' => 'NX', 'brand_id' => 35],
            ['id' => 339, 'name' => 'RC', 'brand_id' => 35],
            ['id' => 340, 'name' => 'RX', 'brand_id' => 35],
            ['id' => 341, 'name' => 'SC', 'brand_id' => 35],
            ['id' => 342, 'name' => 'UX', 'brand_id' => 35],
            ['id' => 343, 'name' => 'Aviator', 'brand_id' => 36],
            ['id' => 344, 'name' => 'Continental', 'brand_id' => 36],
            ['id' => 345, 'name' => 'Mark', 'brand_id' => 36],
            ['id' => 346, 'name' => 'Navigator', 'brand_id' => 36],
            ['id' => 347, 'name' => 'Town Car', 'brand_id' => 36],
            ['id' => 348, 'name' => 'Elise', 'brand_id' => 37],
            ['id' => 349, 'name' => 'Emira', 'brand_id' => 37],
            ['id' => 350, 'name' => 'Esprit', 'brand_id' => 37],
            ['id' => 351, 'name' => 'Evora', 'brand_id' => 37],
            ['id' => 352, 'name' => 'Exige', 'brand_id' => 37],
            ['id' => 353, 'name' => 'Ghibli', 'brand_id' => 38],
            ['id' => 354, 'name' => 'GranCabrio', 'brand_id' => 38],
            ['id' => 355, 'name' => 'GranTurismo', 'brand_id' => 38],
            ['id' => 356, 'name' => 'Grecale', 'brand_id' => 38],
            ['id' => 357, 'name' => 'Levante', 'brand_id' => 38],
            ['id' => 358, 'name' => 'Quattroporte', 'brand_id' => 38],
            ['id' => 359, 'name' => '2', 'brand_id' => 39],
            ['id' => 360, 'name' => '3', 'brand_id' => 39],
            ['id' => 361, 'name' => '5', 'brand_id' => 39],
            ['id' => 362, 'name' => '6', 'brand_id' => 39],
            ['id' => 363, 'name' => 'CX-3', 'brand_id' => 39],
            ['id' => 364, 'name' => 'CX-30', 'brand_id' => 39],
            ['id' => 365, 'name' => 'CX-5', 'brand_id' => 39],
            ['id' => 366, 'name' => 'CX-60', 'brand_id' => 39],
            ['id' => 367, 'name' => 'CX-7', 'brand_id' => 39],
            ['id' => 368, 'name' => 'CX-9', 'brand_id' => 39],
            ['id' => 369, 'name' => 'MX-5', 'brand_id' => 39],
            ['id' => 370, 'name' => 'RX-7', 'brand_id' => 39],
            ['id' => 371, 'name' => 'RX-8', 'brand_id' => 39],
            ['id' => 372, 'name' => '540C', 'brand_id' => 40],
            ['id' => 373, 'name' => '570S', 'brand_id' => 40],
            ['id' => 374, 'name' => '600LT', 'brand_id' => 40],
            ['id' => 375, 'name' => '650S', 'brand_id' => 40],
            ['id' => 376, 'name' => '675LT', 'brand_id' => 40],
            ['id' => 377, 'name' => '720S', 'brand_id' => 40],
            ['id' => 378, 'name' => 'GT', 'brand_id' => 40],
            ['id' => 379, 'name' => 'MP4-12C', 'brand_id' => 40],
            ['id' => 380, 'name' => 'A 35 AMG', 'brand_id' => 41],
            ['id' => 381, 'name' => 'A 45 AMG', 'brand_id' => 41],
            ['id' => 382, 'name' => 'C 43 AMG', 'brand_id' => 41],
            ['id' => 383, 'name' => 'C 63 AMG', 'brand_id' => 41],
            ['id' => 384, 'name' => 'CLA 35 AMG', 'brand_id' => 41],
            ['id' => 385, 'name' => 'CLA 45 AMG', 'brand_id' => 41],
            ['id' => 386, 'name' => 'E 53 AMG', 'brand_id' => 41],
            ['id' => 387, 'name' => 'E 63 AMG', 'brand_id' => 41],
            ['id' => 388, 'name' => 'G 63 AMG', 'brand_id' => 41],
            ['id' => 389, 'name' => 'GT', 'brand_id' => 41],
            ['id' => 390, 'name' => 'S 63 AMG', 'brand_id' => 41],
            ['id' => 391, 'name' => 'A-osztaly', 'brand_id' => 42],
            ['id' => 392, 'name' => 'B-osztaly', 'brand_id' => 42],
            ['id' => 393, 'name' => 'C-osztaly', 'brand_id' => 42],
            ['id' => 394, 'name' => 'Citan', 'brand_id' => 42],
            ['id' => 395, 'name' => 'CLA', 'brand_id' => 42],
            ['id' => 396, 'name' => 'CLC', 'brand_id' => 42],
            ['id' => 397, 'name' => 'CLK', 'brand_id' => 42],
            ['id' => 398, 'name' => 'CLS', 'brand_id' => 42],
            ['id' => 399, 'name' => 'E-osztaly', 'brand_id' => 42],
            ['id' => 400, 'name' => 'EQA', 'brand_id' => 42],
            ['id' => 401, 'name' => 'EQB', 'brand_id' => 42],
            ['id' => 402, 'name' => 'EQC', 'brand_id' => 42],
            ['id' => 403, 'name' => 'EQE', 'brand_id' => 42],
            ['id' => 404, 'name' => 'EQS', 'brand_id' => 42],
            ['id' => 405, 'name' => 'GLA', 'brand_id' => 42],
            ['id' => 406, 'name' => 'GLB', 'brand_id' => 42],
            ['id' => 407, 'name' => 'GLC', 'brand_id' => 42],
            ['id' => 408, 'name' => 'GLE', 'brand_id' => 42],
            ['id' => 409, 'name' => 'GLS', 'brand_id' => 42],
            ['id' => 410, 'name' => 'Marco Polo', 'brand_id' => 42],
            ['id' => 411, 'name' => 'ML', 'brand_id' => 42],
            ['id' => 412, 'name' => 'R-osztaly', 'brand_id' => 42],
            ['id' => 413, 'name' => 'S-osztaly', 'brand_id' => 42],
            ['id' => 414, 'name' => 'SL', 'brand_id' => 42],
            ['id' => 415, 'name' => 'SLC', 'brand_id' => 42],
            ['id' => 416, 'name' => 'Sprinter', 'brand_id' => 42],
            ['id' => 417, 'name' => 'V-osztaly', 'brand_id' => 42],
            ['id' => 418, 'name' => 'Viano', 'brand_id' => 42],
            ['id' => 419, 'name' => 'Vito', 'brand_id' => 42],
            ['id' => 420, 'name' => 'Cougar', 'brand_id' => 43],
            ['id' => 421, 'name' => 'Grand Marquis', 'brand_id' => 43],
            ['id' => 422, 'name' => 'Marauder', 'brand_id' => 43],
            ['id' => 423, 'name' => 'Monterey', 'brand_id' => 43],
            ['id' => 424, 'name' => 'Mountaineer', 'brand_id' => 43],
            ['id' => 425, 'name' => 'Marvel R', 'brand_id' => 44],
            ['id' => 426, 'name' => 'MG3', 'brand_id' => 44],
            ['id' => 427, 'name' => 'MG4', 'brand_id' => 44],
            ['id' => 428, 'name' => 'MG5', 'brand_id' => 44],
            ['id' => 429, 'name' => 'ZS', 'brand_id' => 44],
            ['id' => 430, 'name' => 'ZS EV', 'brand_id' => 44],
            ['id' => 431, 'name' => 'Clubman', 'brand_id' => 45],
            ['id' => 432, 'name' => 'Countryman', 'brand_id' => 45],
            ['id' => 433, 'name' => 'Coupe', 'brand_id' => 45],
            ['id' => 434, 'name' => 'Mini (Hatch)', 'brand_id' => 45],
            ['id' => 435, 'name' => 'Paceman', 'brand_id' => 45],
            ['id' => 436, 'name' => 'Roadster', 'brand_id' => 45],
            ['id' => 437, 'name' => 'ASX', 'brand_id' => 46],
            ['id' => 438, 'name' => 'Colt', 'brand_id' => 46],
            ['id' => 439, 'name' => 'Eclipse Cross', 'brand_id' => 46],
            ['id' => 440, 'name' => 'Galant', 'brand_id' => 46],
            ['id' => 441, 'name' => 'Grandis', 'brand_id' => 46],
            ['id' => 442, 'name' => 'L200', 'brand_id' => 46],
            ['id' => 443, 'name' => 'Lancer', 'brand_id' => 46],
            ['id' => 444, 'name' => 'Outlander', 'brand_id' => 46],
            ['id' => 445, 'name' => 'Pajero', 'brand_id' => 46],
            ['id' => 446, 'name' => 'Space Star', 'brand_id' => 46],
            ['id' => 447, 'name' => '4/4', 'brand_id' => 47],
            ['id' => 448, 'name' => 'Plus 4', 'brand_id' => 47],
            ['id' => 449, 'name' => 'Plus 8', 'brand_id' => 47],
            ['id' => 450, 'name' => 'Roadster', 'brand_id' => 47],
            ['id' => 451, 'name' => 'Marina', 'brand_id' => 48],
            ['id' => 452, 'name' => 'Minor', 'brand_id' => 48],
            ['id' => 453, 'name' => 'Oxford', 'brand_id' => 48],
            ['id' => 454, 'name' => '350Z', 'brand_id' => 49],
            ['id' => 455, 'name' => '370Z', 'brand_id' => 49],
            ['id' => 456, 'name' => 'Almera', 'brand_id' => 49],
            ['id' => 457, 'name' => 'Juke', 'brand_id' => 49],
            ['id' => 458, 'name' => 'Leaf', 'brand_id' => 49],
            ['id' => 459, 'name' => 'Micra', 'brand_id' => 49],
            ['id' => 460, 'name' => 'Murano', 'brand_id' => 49],
            ['id' => 461, 'name' => 'Navara', 'brand_id' => 49],
            ['id' => 462, 'name' => 'Note', 'brand_id' => 49],
            ['id' => 463, 'name' => 'Pathfinder', 'brand_id' => 49],
            ['id' => 464, 'name' => 'Patrol', 'brand_id' => 49],
            ['id' => 465, 'name' => 'Primera', 'brand_id' => 49],
            ['id' => 466, 'name' => 'Qashqai', 'brand_id' => 49],
            ['id' => 467, 'name' => 'Terrano', 'brand_id' => 49],
            ['id' => 468, 'name' => 'X-Trail', 'brand_id' => 49],
            ['id' => 469, 'name' => 'Alero', 'brand_id' => 50],
            ['id' => 470, 'name' => 'Cutlass', 'brand_id' => 50],
            ['id' => 471, 'name' => 'Eighty-Eight', 'brand_id' => 50],
            ['id' => 472, 'name' => 'Intrigue', 'brand_id' => 50],
            ['id' => 473, 'name' => 'Adam', 'brand_id' => 51],
            ['id' => 474, 'name' => 'Agila', 'brand_id' => 51],
            ['id' => 475, 'name' => 'Ampera', 'brand_id' => 51],
            ['id' => 476, 'name' => 'Antara', 'brand_id' => 51],
            ['id' => 477, 'name' => 'Astra', 'brand_id' => 51],
            ['id' => 478, 'name' => 'Corsa', 'brand_id' => 51],
            ['id' => 479, 'name' => 'Crossland', 'brand_id' => 51],
            ['id' => 480, 'name' => 'Frontera', 'brand_id' => 51],
            ['id' => 481, 'name' => 'Insignia', 'brand_id' => 51],
            ['id' => 482, 'name' => 'Meriva', 'brand_id' => 51],
            ['id' => 483, 'name' => 'Mokka', 'brand_id' => 51],
            ['id' => 484, 'name' => 'Omega', 'brand_id' => 51],
            ['id' => 485, 'name' => 'Signum', 'brand_id' => 51],
            ['id' => 486, 'name' => 'Vectra', 'brand_id' => 51],
            ['id' => 487, 'name' => 'Zafira', 'brand_id' => 51],
            ['id' => 488, 'name' => '107', 'brand_id' => 52],
            ['id' => 489, 'name' => '108', 'brand_id' => 52],
            ['id' => 490, 'name' => '2008', 'brand_id' => 52],
            ['id' => 491, 'name' => '206', 'brand_id' => 52],
            ['id' => 492, 'name' => '207', 'brand_id' => 52],
            ['id' => 493, 'name' => '208', 'brand_id' => 52],
            ['id' => 494, 'name' => '3008', 'brand_id' => 52],
            ['id' => 495, 'name' => '301', 'brand_id' => 52],
            ['id' => 496, 'name' => '306', 'brand_id' => 52],
            ['id' => 497, 'name' => '307', 'brand_id' => 52],
            ['id' => 498, 'name' => '308', 'brand_id' => 52],
            ['id' => 499, 'name' => '406', 'brand_id' => 52],
            ['id' => 500, 'name' => '407', 'brand_id' => 52],
            ['id' => 501, 'name' => '5008', 'brand_id' => 52],
            ['id' => 502, 'name' => '508', 'brand_id' => 52],
            ['id' => 503, 'name' => 'Partner', 'brand_id' => 52],
            ['id' => 504, 'name' => 'Rifter', 'brand_id' => 52],
            ['id' => 505, 'name' => 'Breeze', 'brand_id' => 53],
            ['id' => 506, 'name' => 'Neon', 'brand_id' => 53],
            ['id' => 507, 'name' => 'Voyager', 'brand_id' => 53],
            ['id' => 508, 'name' => '1', 'brand_id' => 54],
            ['id' => 509, 'name' => '2', 'brand_id' => 54],
            ['id' => 510, 'name' => '3', 'brand_id' => 54],
            ['id' => 511, 'name' => '4', 'brand_id' => 54],
            ['id' => 512, 'name' => '125p', 'brand_id' => 55],
            ['id' => 513, 'name' => '126p', 'brand_id' => 55],
            ['id' => 514, 'name' => 'Firebird', 'brand_id' => 56],
            ['id' => 515, 'name' => 'G6', 'brand_id' => 56],
            ['id' => 516, 'name' => 'Grand Prix', 'brand_id' => 56],
            ['id' => 517, 'name' => 'Solstice', 'brand_id' => 56],
            ['id' => 518, 'name' => 'Trans Am', 'brand_id' => 56],
            ['id' => 519, 'name' => '911', 'brand_id' => 57],
            ['id' => 520, 'name' => '918 Spyder', 'brand_id' => 57],
            ['id' => 521, 'name' => 'Boxster', 'brand_id' => 57],
            ['id' => 522, 'name' => 'Cayenne', 'brand_id' => 57],
            ['id' => 523, 'name' => 'Cayman', 'brand_id' => 57],
            ['id' => 524, 'name' => 'Macan', 'brand_id' => 57],
            ['id' => 525, 'name' => 'Panamera', 'brand_id' => 57],
            ['id' => 526, 'name' => 'Taycan', 'brand_id' => 57],
            ['id' => 527, 'name' => 'Gen-2', 'brand_id' => 58],
            ['id' => 528, 'name' => 'Persona', 'brand_id' => 58],
            ['id' => 529, 'name' => 'Satria', 'brand_id' => 58],
            ['id' => 530, 'name' => 'Arkana', 'brand_id' => 59],
            ['id' => 531, 'name' => 'Austral', 'brand_id' => 59],
            ['id' => 532, 'name' => 'Captur', 'brand_id' => 59],
            ['id' => 533, 'name' => 'Clio', 'brand_id' => 59],
            ['id' => 534, 'name' => 'Espace', 'brand_id' => 59],
            ['id' => 535, 'name' => 'Fluence', 'brand_id' => 59],
            ['id' => 536, 'name' => 'Grand Scenic', 'brand_id' => 59],
            ['id' => 537, 'name' => 'Kadjar', 'brand_id' => 59],
            ['id' => 538, 'name' => 'Kangoo', 'brand_id' => 59],
            ['id' => 539, 'name' => 'Koleos', 'brand_id' => 59],
            ['id' => 540, 'name' => 'Laguna', 'brand_id' => 59],
            ['id' => 541, 'name' => 'Megane', 'brand_id' => 59],
            ['id' => 542, 'name' => 'Modus', 'brand_id' => 59],
            ['id' => 543, 'name' => 'Scenic', 'brand_id' => 59],
            ['id' => 544, 'name' => 'Talisman', 'brand_id' => 59],
            ['id' => 545, 'name' => 'Twingo', 'brand_id' => 59],
            ['id' => 546, 'name' => 'Vel Satis', 'brand_id' => 59],
            ['id' => 547, 'name' => 'Zoe', 'brand_id' => 59],
            ['id' => 548, 'name' => 'Cullinan', 'brand_id' => 60],
            ['id' => 549, 'name' => 'Dawn', 'brand_id' => 60],
            ['id' => 550, 'name' => 'Ghost', 'brand_id' => 60],
            ['id' => 551, 'name' => 'Phantom', 'brand_id' => 60],
            ['id' => 552, 'name' => 'Silver Shadow', 'brand_id' => 60],
            ['id' => 553, 'name' => 'Wraith', 'brand_id' => 60],
            ['id' => 554, 'name' => '9-3', 'brand_id' => 61],
            ['id' => 555, 'name' => '9-5', 'brand_id' => 61],
            ['id' => 556, 'name' => '9-7X', 'brand_id' => 61],
            ['id' => 557, 'name' => '900', 'brand_id' => 61],
            ['id' => 558, 'name' => '9000', 'brand_id' => 61],
            ['id' => 559, 'name' => 'Alhambra', 'brand_id' => 62],
            ['id' => 560, 'name' => 'Altea', 'brand_id' => 62],
            ['id' => 561, 'name' => 'Arona', 'brand_id' => 62],
            ['id' => 562, 'name' => 'Ateca', 'brand_id' => 62],
            ['id' => 563, 'name' => 'Cordoba', 'brand_id' => 62],
            ['id' => 564, 'name' => 'Ibiza', 'brand_id' => 62],
            ['id' => 565, 'name' => 'Leon', 'brand_id' => 62],
            ['id' => 566, 'name' => 'Mii', 'brand_id' => 62],
            ['id' => 567, 'name' => 'Toledo', 'brand_id' => 62],
            ['id' => 568, 'name' => 'Forfour', 'brand_id' => 63],
            ['id' => 569, 'name' => 'Fortwo', 'brand_id' => 63],
            ['id' => 570, 'name' => 'Roadster', 'brand_id' => 63],
            ['id' => 571, 'name' => 'Actyon', 'brand_id' => 64],
            ['id' => 572, 'name' => 'Korando', 'brand_id' => 64],
            ['id' => 573, 'name' => 'Kyron', 'brand_id' => 64],
            ['id' => 574, 'name' => 'Musso', 'brand_id' => 64],
            ['id' => 575, 'name' => 'Rexton', 'brand_id' => 64],
            ['id' => 576, 'name' => 'Tivoli', 'brand_id' => 64],
            ['id' => 577, 'name' => 'BRZ', 'brand_id' => 65],
            ['id' => 578, 'name' => 'Forester', 'brand_id' => 65],
            ['id' => 579, 'name' => 'Impreza', 'brand_id' => 65],
            ['id' => 580, 'name' => 'Legacy', 'brand_id' => 65],
            ['id' => 581, 'name' => 'Levorg', 'brand_id' => 65],
            ['id' => 582, 'name' => 'Outback', 'brand_id' => 65],
            ['id' => 583, 'name' => 'WRX', 'brand_id' => 65],
            ['id' => 584, 'name' => 'Alto', 'brand_id' => 66],
            ['id' => 585, 'name' => 'Baleno', 'brand_id' => 66],
            ['id' => 586, 'name' => 'Grand Vitara', 'brand_id' => 66],
            ['id' => 587, 'name' => 'Ignis', 'brand_id' => 66],
            ['id' => 588, 'name' => 'Jimny', 'brand_id' => 66],
            ['id' => 589, 'name' => 'Liana', 'brand_id' => 66],
            ['id' => 590, 'name' => 'Splash', 'brand_id' => 66],
            ['id' => 591, 'name' => 'Swift', 'brand_id' => 66],
            ['id' => 592, 'name' => 'SX4', 'brand_id' => 66],
            ['id' => 593, 'name' => 'Vitara', 'brand_id' => 66],
            ['id' => 594, 'name' => 'Citigo', 'brand_id' => 67],
            ['id' => 595, 'name' => 'Fabia', 'brand_id' => 67],
            ['id' => 596, 'name' => 'Karoq', 'brand_id' => 67],
            ['id' => 597, 'name' => 'Kodiaq', 'brand_id' => 67],
            ['id' => 598, 'name' => 'Octavia', 'brand_id' => 67],
            ['id' => 599, 'name' => 'Rapid', 'brand_id' => 67],
            ['id' => 600, 'name' => 'Roomster', 'brand_id' => 67],
            ['id' => 601, 'name' => 'Scala', 'brand_id' => 67],
            ['id' => 602, 'name' => 'Superb', 'brand_id' => 67],
            ['id' => 603, 'name' => 'Yeti', 'brand_id' => 67],
            ['id' => 604, 'name' => 'Model 3', 'brand_id' => 68],
            ['id' => 605, 'name' => 'Model S', 'brand_id' => 68],
            ['id' => 606, 'name' => 'Model X', 'brand_id' => 68],
            ['id' => 607, 'name' => 'Model Y', 'brand_id' => 68],
            ['id' => 608, 'name' => 'Roadster', 'brand_id' => 68],
            ['id' => 609, 'name' => 'Auris', 'brand_id' => 69],
            ['id' => 610, 'name' => 'Avensis', 'brand_id' => 69],
            ['id' => 611, 'name' => 'Aygo', 'brand_id' => 69],
            ['id' => 612, 'name' => 'C-HR', 'brand_id' => 69],
            ['id' => 613, 'name' => 'Camry', 'brand_id' => 69],
            ['id' => 614, 'name' => 'Celica', 'brand_id' => 69],
            ['id' => 615, 'name' => 'Corolla', 'brand_id' => 69],
            ['id' => 616, 'name' => 'GR86', 'brand_id' => 69],
            ['id' => 617, 'name' => 'Hilux', 'brand_id' => 69],
            ['id' => 618, 'name' => 'Land Cruiser', 'brand_id' => 69],
            ['id' => 619, 'name' => 'Mirai', 'brand_id' => 69],
            ['id' => 620, 'name' => 'Prius', 'brand_id' => 69],
            ['id' => 621, 'name' => 'RAV4', 'brand_id' => 69],
            ['id' => 622, 'name' => 'Supra', 'brand_id' => 69],
            ['id' => 623, 'name' => 'Urban Cruiser', 'brand_id' => 69],
            ['id' => 624, 'name' => 'Verso', 'brand_id' => 69],
            ['id' => 625, 'name' => 'Yaris', 'brand_id' => 69],
            ['id' => 626, 'name' => '1.1', 'brand_id' => 70],
            ['id' => 627, 'name' => '601', 'brand_id' => 70],
            ['id' => 628, 'name' => '3151', 'brand_id' => 71],
            ['id' => 629, 'name' => 'Hunter', 'brand_id' => 71],
            ['id' => 630, 'name' => 'Patriot', 'brand_id' => 71],
            ['id' => 631, 'name' => 'Astra', 'brand_id' => 72],
            ['id' => 632, 'name' => 'Corsa', 'brand_id' => 72],
            ['id' => 633, 'name' => 'Insignia', 'brand_id' => 72],
            ['id' => 634, 'name' => 'Mokka', 'brand_id' => 72],
            ['id' => 635, 'name' => 'Zafira', 'brand_id' => 72],
            ['id' => 636, 'name' => 'GAZ-21', 'brand_id' => 73],
            ['id' => 637, 'name' => 'GAZ-24', 'brand_id' => 73],
            ['id' => 638, 'name' => 'GAZ-3102', 'brand_id' => 73],
            ['id' => 639, 'name' => 'Amarok', 'brand_id' => 74],
            ['id' => 640, 'name' => 'Arteon', 'brand_id' => 74],
            ['id' => 641, 'name' => 'Beetle', 'brand_id' => 74],
            ['id' => 642, 'name' => 'Bora', 'brand_id' => 74],
            ['id' => 643, 'name' => 'Caddy', 'brand_id' => 74],
            ['id' => 644, 'name' => 'Corrado', 'brand_id' => 74],
            ['id' => 645, 'name' => 'Eos', 'brand_id' => 74],
            ['id' => 646, 'name' => 'Fox', 'brand_id' => 74],
            ['id' => 647, 'name' => 'Golf', 'brand_id' => 74],
            ['id' => 648, 'name' => 'ID.3', 'brand_id' => 74],
            ['id' => 649, 'name' => 'ID.4', 'brand_id' => 74],
            ['id' => 650, 'name' => 'ID.5', 'brand_id' => 74],
            ['id' => 651, 'name' => 'Jetta', 'brand_id' => 74],
            ['id' => 652, 'name' => 'Lupo', 'brand_id' => 74],
            ['id' => 653, 'name' => 'Passat', 'brand_id' => 74],
            ['id' => 654, 'name' => 'Polo', 'brand_id' => 74],
            ['id' => 655, 'name' => 'Scirocco', 'brand_id' => 74],
            ['id' => 656, 'name' => 'Sharan', 'brand_id' => 74],
            ['id' => 657, 'name' => 'T-Cross', 'brand_id' => 74],
            ['id' => 658, 'name' => 'T-Roc', 'brand_id' => 74],
            ['id' => 659, 'name' => 'Tiguan', 'brand_id' => 74],
            ['id' => 660, 'name' => 'Touareg', 'brand_id' => 74],
            ['id' => 661, 'name' => 'Touran', 'brand_id' => 74],
            ['id' => 662, 'name' => 'Transporter', 'brand_id' => 74],
            ['id' => 663, 'name' => 'Up', 'brand_id' => 74],
            ['id' => 664, 'name' => 'C30', 'brand_id' => 75],
            ['id' => 665, 'name' => 'C40', 'brand_id' => 75],
            ['id' => 666, 'name' => 'S40', 'brand_id' => 75],
            ['id' => 667, 'name' => 'S60', 'brand_id' => 75],
            ['id' => 668, 'name' => 'S80', 'brand_id' => 75],
            ['id' => 669, 'name' => 'S90', 'brand_id' => 75],
            ['id' => 670, 'name' => 'V40', 'brand_id' => 75],
            ['id' => 671, 'name' => 'V50', 'brand_id' => 75],
            ['id' => 672, 'name' => 'V60', 'brand_id' => 75],
            ['id' => 673, 'name' => 'V70', 'brand_id' => 75],
            ['id' => 674, 'name' => 'V90', 'brand_id' => 75],
            ['id' => 675, 'name' => 'XC40', 'brand_id' => 75],
            ['id' => 676, 'name' => 'XC60', 'brand_id' => 75],
            ['id' => 677, 'name' => 'XC70', 'brand_id' => 75],
            ['id' => 678, 'name' => 'XC90', 'brand_id' => 75],
            ['id' => 679, 'name' => '1.3', 'brand_id' => 76],
            ['id' => 680, 'name' => '353', 'brand_id' => 76],
            ['id' => 681, 'name' => 'G3', 'brand_id' => 77],
            ['id' => 682, 'name' => 'G6', 'brand_id' => 77],
            ['id' => 683, 'name' => 'G9', 'brand_id' => 77],
            ['id' => 684, 'name' => 'P7', 'brand_id' => 77],
            ['id' => 685, 'name' => '10', 'brand_id' => 78],
            ['id' => 686, 'name' => '101', 'brand_id' => 78],
            ['id' => 687, 'name' => '750', 'brand_id' => 78]
        ]);
    }
}
