<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CompanyServiceSeeder extends Seeder
{
    public function run(): void
    {

        DB::table('company_service')->insert([
            ['company_id' => 1, 'category_id' => 5],
            ['company_id' => 1, 'category_id' => 6],
            ['company_id' => 1, 'category_id' => 7],
            ['company_id' => 1, 'category_id' => 8],
            ['company_id' => 1, 'category_id' => 10],
            ['company_id' => 1, 'category_id' => 11],
            ['company_id' => 1, 'category_id' => 12],
            ['company_id' => 2, 'category_id' => 1],
            ['company_id' => 2, 'category_id' => 2],
            ['company_id' => 2, 'category_id' => 3],
            ['company_id' => 2, 'category_id' => 4],
            ['company_id' => 2, 'category_id' => 5],
            ['company_id' => 2, 'category_id' => 6],
            ['company_id' => 2, 'category_id' => 14],
            ['company_id' => 3, 'category_id' => 1],
            ['company_id' => 3, 'category_id' => 2],
            ['company_id' => 3, 'category_id' => 5],
            ['company_id' => 3, 'category_id' => 6],
            ['company_id' => 3, 'category_id' => 8],
            ['company_id' => 3, 'category_id' => 9],
            ['company_id' => 3, 'category_id' => 14],
            ['company_id' => 4, 'category_id' => 1],
            ['company_id' => 4, 'category_id' => 3],
            ['company_id' => 4, 'category_id' => 4],
            ['company_id' => 4, 'category_id' => 5],
            ['company_id' => 4, 'category_id' => 6],
            ['company_id' => 4, 'category_id' => 7],
            ['company_id' => 4, 'category_id' => 8],
            ['company_id' => 4, 'category_id' => 14],
            ['company_id' => 5, 'category_id' => 4],
            ['company_id' => 5, 'category_id' => 8],
            ['company_id' => 5, 'category_id' => 14],
            ['company_id' => 5, 'category_id' => 15],
            ['company_id' => 6, 'category_id' => 1],
            ['company_id' => 6, 'category_id' => 2],
            ['company_id' => 6, 'category_id' => 5],
            ['company_id' => 6, 'category_id' => 6],
            ['company_id' => 6, 'category_id' => 8],
            ['company_id' => 6, 'category_id' => 11],
            ['company_id' => 6, 'category_id' => 12],
            ['company_id' => 6, 'category_id' => 15],
            ['company_id' => 7, 'category_id' => 1],
            ['company_id' => 7, 'category_id' => 2],
            ['company_id' => 7, 'category_id' => 6],
            ['company_id' => 7, 'category_id' => 10],
            ['company_id' => 7, 'category_id' => 11],
            ['company_id' => 7, 'category_id' => 12],
            ['company_id' => 7, 'category_id' => 13],
            ['company_id' => 7, 'category_id' => 14],
            ['company_id' => 8, 'category_id' => 1],
            ['company_id' => 8, 'category_id' => 3],
            ['company_id' => 8, 'category_id' => 7],
            ['company_id' => 8, 'category_id' => 12],
            ['company_id' => 8, 'category_id' => 13],
            ['company_id' => 9, 'category_id' => 1],
            ['company_id' => 9, 'category_id' => 3],
            ['company_id' => 9, 'category_id' => 5],
            ['company_id' => 9, 'category_id' => 6],
            ['company_id' => 9, 'category_id' => 8],
            ['company_id' => 9, 'category_id' => 11],
            ['company_id' => 10, 'category_id' => 3],
            ['company_id' => 10, 'category_id' => 5],
            ['company_id' => 10, 'category_id' => 8],
            ['company_id' => 10, 'category_id' => 11],
            ['company_id' => 10, 'category_id' => 14],
            ['company_id' => 11, 'category_id' => 3],
            ['company_id' => 11, 'category_id' => 6],
            ['company_id' => 11, 'category_id' => 10],
            ['company_id' => 11, 'category_id' => 11],
            ['company_id' => 12, 'category_id' => 2],
            ['company_id' => 12, 'category_id' => 4],
            ['company_id' => 12, 'category_id' => 9],
            ['company_id' => 12, 'category_id' => 12],
            ['company_id' => 12, 'category_id' => 14],
            ['company_id' => 13, 'category_id' => 2],
            ['company_id' => 13, 'category_id' => 3],
            ['company_id' => 13, 'category_id' => 7],
            ['company_id' => 13, 'category_id' => 13],
            ['company_id' => 14, 'category_id' => 2],
            ['company_id' => 14, 'category_id' => 5],
            ['company_id' => 14, 'category_id' => 12],
            ['company_id' => 14, 'category_id' => 13],
            ['company_id' => 14, 'category_id' => 15],
            ['company_id' => 15, 'category_id' => 1],
            ['company_id' => 15, 'category_id' => 11],
            ['company_id' => 15, 'category_id' => 13],
            ['company_id' => 15, 'category_id' => 15],
            ['company_id' => 16, 'category_id' => 1],
            ['company_id' => 16, 'category_id' => 2],
            ['company_id' => 16, 'category_id' => 3],
            ['company_id' => 16, 'category_id' => 8],
            ['company_id' => 16, 'category_id' => 9],
            ['company_id' => 17, 'category_id' => 3],
            ['company_id' => 17, 'category_id' => 5],
            ['company_id' => 17, 'category_id' => 9],
            ['company_id' => 17, 'category_id' => 12],
            ['company_id' => 18, 'category_id' => 1],
            ['company_id' => 18, 'category_id' => 3],
            ['company_id' => 18, 'category_id' => 5],
            ['company_id' => 18, 'category_id' => 8],
            ['company_id' => 18, 'category_id' => 11],
            ['company_id' => 19, 'category_id' => 3],
            ['company_id' => 19, 'category_id' => 6],
            ['company_id' => 19, 'category_id' => 13],
            ['company_id' => 19, 'category_id' => 15],
            ['company_id' => 20, 'category_id' => 1],
            ['company_id' => 20, 'category_id' => 2],
            ['company_id' => 20, 'category_id' => 3],
            ['company_id' => 20, 'category_id' => 5],
            ['company_id' => 20, 'category_id' => 7],
            ['company_id' => 20, 'category_id' => 10],
            ['company_id' => 21, 'category_id' => 1],
            ['company_id' => 21, 'category_id' => 6],
            ['company_id' => 21, 'category_id' => 7],
            ['company_id' => 21, 'category_id' => 8],
            ['company_id' => 21, 'category_id' => 14],
            ['company_id' => 22, 'category_id' => 3],
            ['company_id' => 22, 'category_id' => 5],
            ['company_id' => 22, 'category_id' => 6],
            ['company_id' => 22, 'category_id' => 13],
            ['company_id' => 23, 'category_id' => 3],
            ['company_id' => 23, 'category_id' => 6],
            ['company_id' => 23, 'category_id' => 7],
            ['company_id' => 23, 'category_id' => 8],
            ['company_id' => 23, 'category_id' => 15]
        ]);
    }
}
